INSERT INTO books (title, version, borrowed) VALUES 
('Herr der Ringe', '1980', 'false'),
('Hobbit', 'first version', 'false'),
('Enderman', '1.1', 'false'),
('Enders Game', '8', 'false'),
('The Ring', 'TV', 'false'),
('Uldar', '2', 'false'),
('The Name of the Book', '0', 'false'),
('Pascal', '1', 'false'),
('Head first Java', 'First Edition', 'true'),
('Head first Design Patterns', 'Second Edition', 'true'),
('Anders', '7', 'false'),
('Stanley Parable', 'Sequel', 'false'),
('Youtube - get rich quick', 'Scam edition', 'false'),
('Star Wars', '5', 'false');